### ISSUE TITLE
Error when cloning one yandex mail account to another

### ISSUE THREAD

**Issue by gecube** [jarus/imap_copy#11]
Hello!

I've faced with next problem. I want to recursively copy all messages from one mailbox to another. Both mails are located on YANDEX mail server. I use next command and get next output:

```
# python imapcopy2.py -r -c imap.yandex.ru:993 XXXXXX@YANDEX.RU:PASSWORD imap.yandex.ru:993 XXXXXX@YANDEX.RU:PASSWORD "" ""
2016-05-31 11:29:14,356 - INFO - Connect to source (imap.yandex.ru)
2016-05-31 11:29:14,965 - INFO - Authenticate at source
2016-05-31 11:29:15,062 - INFO - source connection established
2016-05-31 11:29:15,289 - INFO - Connect to destination (imap.yandex.ru)
2016-05-31 11:29:15,855 - INFO - Authenticate at destination
2016-05-31 11:29:16,005 - INFO - destination connection established
2016-05-31 11:29:16,245 - INFO - Getting list of mailboxes under 
2016-05-31 11:29:16,470 - INFO - Recursing into &BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-
2016-05-31 11:29:16,470 - INFO - Getting list of mailboxes under &BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-
2016-05-31 11:29:16,862 - INFO - Create destination mailbox |&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-
2016-05-31 11:29:17,231 - INFO - Looking for mails in &BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-
2016-05-31 11:29:17,495 - INFO - Start copy &BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1- => |&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1- (180 mails)
2016-05-31 11:29:18,046 - INFO - Copy mail 1 of 180 (copy_count=1, md5(message)=915fa7e6ded9106af3fc906f715a75d9)
2016-05-31 11:29:18,485 - INFO - Copy mail 2 of 180 (copy_count=2, md5(message)=eff927cff1aef0bf8af2f036ad04c968)
2016-05-31 11:29:18,944 - INFO - Copy mail 3 of 180 (copy_count=3, md5(message)=5780dc688ad4ead68e24dc1804885853)
2016-05-31 11:29:19,382 - INFO - Copy mail 4 of 180 (copy_count=4, md5(message)=e948f76ce9bfef6d0ced0f6d0beda919)
2016-05-31 11:29:19,794 - INFO - Copy mail 5 of 180 (copy_count=5, md5(message)=0cd7c9aea9fc3f8c94e4a398d7960cc7)
2016-05-31 11:29:20,249 - INFO - Copy mail 6 of 180 (copy_count=6, md5(message)=43b26808b1b154c403f57d07fc77ae0f)
2016-05-31 11:29:20,732 - INFO - Copy mail 7 of 180 (copy_count=7, md5(message)=d9857d59699b48ae8328ba0ad784e8e2)
2016-05-31 11:29:21,587 - INFO - Copy mail 8 of 180 (copy_count=8, md5(message)=72dd4dd5c85d6ac1fe98c90b93228425)
2016-05-31 11:29:22,046 - INFO - Copy mail 9 of 180 (copy_count=9, md5(message)=dc5f9ba1421f6ca89a2e6de05190ea04)
2016-05-31 11:29:22,464 - INFO - Copy mail 10 of 180 (copy_count=10, md5(message)=248a7e8f5bcbb5ed42868035fcf90b26)
2016-05-31 11:29:22,902 - INFO - Copy mail 11 of 180 (copy_count=11, md5(message)=9cad4c67446d502e8c773c83a2618425)
2016-05-31 11:29:23,322 - INFO - Copy mail 12 of 180 (copy_count=12, md5(message)=c39b1bc89cd95d33b6395ca763f4c49a)
2016-05-31 11:29:23,750 - INFO - Copy mail 13 of 180 (copy_count=13, md5(message)=78ea52b0dcc1cd5a0ccef8aa170e27aa)
2016-05-31 11:29:24,208 - INFO - Copy mail 14 of 180 (copy_count=14, md5(message)=f9b51ea22ee441b392fff1167352cd87)
2016-05-31 11:29:24,637 - INFO - Copy mail 15 of 180 (copy_count=15, md5(message)=2870d5d1aaa606a38d0ad2de8e148dd7)
2016-05-31 11:29:25,083 - INFO - Copy mail 16 of 180 (copy_count=16, md5(message)=f2dd880dcc6012d64b34da8191548aef)
2016-05-31 11:29:26,238 - INFO - Copy mail 17 of 180 (copy_count=17, md5(message)=a34d02cd9a6759136080ff19a9895d23)
2016-05-31 11:29:26,691 - INFO - Copy mail 18 of 180 (copy_count=18, md5(message)=8fe1a29f9507de48a3634369f3773cbc)
2016-05-31 11:29:27,113 - INFO - Copy mail 19 of 180 (copy_count=19, md5(message)=8acf14e49bdf3ce8f3670b101b7ef8b6)
2016-05-31 11:29:27,529 - INFO - Copy mail 20 of 180 (copy_count=20, md5(message)=0f97d518a239ea19608d8d5d2b49af33)
2016-05-31 11:29:27,951 - INFO - Copy mail 21 of 180 (copy_count=21, md5(message)=52976ca5b7e97ae27798b413ac56c553)
2016-05-31 11:29:28,382 - INFO - Copy mail 22 of 180 (copy_count=22, md5(message)=1a46748406a013b236d43a168c9ab64f)
2016-05-31 11:29:28,879 - INFO - Copy mail 23 of 180 (copy_count=23, md5(message)=46f3f5a07092d3e17e70eb8d331b5c15)
2016-05-31 11:29:29,322 - INFO - Copy mail 24 of 180 (copy_count=24, md5(message)=36a01975540787f7e158da41d9c423dc)

2016-05-31 11:30:03,667 - INFO - Copy mail 25 of 180 (copy_count=25, md5(message)=f9d1a379f9389eacc5b7c0df51d540dd)
2016-05-31 11:30:04,262 - INFO - Copy mail 26 of 180 (copy_count=26, md5(message)=277233f3909c9db533322b833513d166)
2016-05-31 11:30:04,814 - INFO - Close mailbox on source
2016-05-31 11:30:04,814 - INFO - Disconnect from source server
2016-05-31 11:30:04,898 - INFO - Disconnect from destination server
Traceback (most recent call last):
  File "imapcopy2.py", line 266, in <module>
    main()
  File "imapcopy2.py", line 260, in main
    imap_copy.run()
  File "imapcopy2.py", line 179, in run
    self.copy(source_mailbox, destination_mailbox, self.skip, self.limit)
  File "imapcopy2.py", line 105, in copy
    skip, limit, recurse_level + 1)
  File "imapcopy2.py", line 158, in copy
    destination_mailbox, flags, msgDate, message
  File "/usr/local/lib/python2.7/imaplib.py", line 337, in append
    return self._simple_command(name, mailbox, flags, date_time)
  File "/usr/local/lib/python2.7/imaplib.py", line 1088, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python2.7/imaplib.py", line 918, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: APPEND command error: BAD ['Command syntax error. sc=HTHlNx5Ix8c8_310929_24o']

```

**Comment by rehoehle** [comment]
Some problem here with 1und1 inbox. Some message are copied and then i get an error.

**Comment by gecube** [comment]
I used another method which is 100% working. It needs to have installed Outlook on some PC. You download there all mail and then just move it to another e-mail box. It is slow, but probably reliable.

**Comment by rehoehle** [comment]
@gecube  i know that... but that is the way i don't want... this is my normal way then i don't need that script :D
