### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by SR-gh** [jarus/imap_copy#12]
Crashed during copy on destination server.
Your crash message suggests that I should report the problem. Here is what I can report.

Command line (anonymised) :

`python imapcopy.py -c "imap.yyy.net:993" "a@b:c" "109.yyy.xxx.zz:993" "a@b:c" "INBOX" "INBOX/anciens" --recurse`

Crash message :

```
2017-03-12 10:27:22,543 - INFO - Copy mail 999 of 1016 (copy_count=999, md5(message)=xxx...xxx)
2017-03-12 10:27:22,586 - INFO - Close mailbox on source
2017-03-12 10:27:22,587 - INFO - Disconnect from source server
2017-03-12 10:27:22,603 - INFO - Disconnect from destination server
Traceback (most recent call last):
  File "imapcopy.py", line 265, in <module>
    main()
  File "imapcopy.py", line 259, in main
    imap_copy.run()
  File "imapcopy.py", line 178, in run
    self.copy(source_mailbox, destination_mailbox, self.skip, self.limit)
  File "imapcopy.py", line 152, in copy
    flags = data[1][8:][:-2]  # Not perfect.. Waiting for bug reports
IndexError: list index out of range

```

**Comment by styks1111** [comment]
I get a similar issue except for me, hour is out of range.

```
2017-08-22 10:25:56,618 - INFO - Copy mail 10772 of 23717 (copy_count=1482, md5(message)=943981bed2001cb43dea9036d4bb159c)
2017-08-22 10:25:56,757 - INFO - Close mailbox on source
2017-08-22 10:25:56,757 - INFO - Disconnect from source server
2017-08-22 10:25:56,879 - INFO - Close mailbox on destination
2017-08-22 10:25:56,880 - INFO - Disconnect from destination server
Traceback (most recent call last):
  File "imapcopy.py", line 265, in <module>
    main()
  File "imapcopy.py", line 259, in main
    imap_copy.run()
  File "imapcopy.py", line 178, in run
    self.copy(source_mailbox, destination_mailbox, self.skip, self.limit)
  File "imapcopy.py", line 157, in copy
    destination_mailbox, flags, msgDate, message
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 333, in append
    date_time = Time2Internaldate(date_time)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1421, in Time2Internaldate
    dt = time.strftime("%d-%b-%Y %H:%M:%S", tt)
ValueError: hour out of range
```
